SET (CPACK_PACKAGE_NAME "${PROJECT_NAME}")
SET (CPACK_PACKAGE_DESCRIPTION_SUMMARY "Milx Web Application Framework for C++")
SET (CPACK_PACKAGE_DESCRIPTION_FILE "README")
SET (CPACK_PACKAGE_VENDOR "Carlos Junior")
SET (CPACK_PACKAGE_INSTALL_DIRECTORY ${CPACK_PACKAGE_NAME})
SET (CPACK_RESOURCE_FILE_LICENSE "LICENSE")

SET (CPACK_SOURCE_IGNORE_FILES "~$;[.]swp$;/[.]svn/;/[.]git/;.gitignore;/build/;tags;cscope.*")
SET (CPACK_SOURCE_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}")
SET (CPACK_PACKAGE_FILE_NAME ${APPLICATION_NAME}-${CPACK_PACKAGE_VERSION})

SET (CPACK_PACKAGE_VERSION_MAJOR "${PROJECT_VERSION_MAJOR}")
SET (CPACK_PACKAGE_VERSION_MINOR "${PROJECT_VERSION_MINOR}")
SET (CPACK_PACKAGE_VERSION_PATCH "${PROJECT_VERSION_PATCH}")
SET (CPACK_PACKAGE_VERSION "${PROJECT_VERSION}")

SET (CPACK_PACKAGE_CONTACT "me@xjunior.me")

INCLUDE (CPack)
