SET (PROJECT_VERSION_MAJOR "0")
SET (PROJECT_VERSION_MINOR "5")
SET (PROJECT_VERSION_PATCH "0")
SET (PROJECT_VERSION "${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH}")

SET (SHARE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}/share" CACHE PATH "Shared dir" FORCE)
SET (PROJECT_HOME ${SHARE_INSTALL_PREFIX}/${PROJECT_NAME})
SET (PROJECT_PUBLIC_INCLUDE_DIR "${CMAKE_SOURCE_DIR}/include"
  CACHE INTERNAL "${PROJECT_NAME} public include dir")
